package report

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"github.com/liemreny/subtakeover/internal/storage"
)

// cleanJSONArr parses a JSON array string like `["a","b"]` into "a, b".
func cleanJSONArr(raw string) string {
	var arr []string
	if err := json.Unmarshal([]byte(raw), &arr); err != nil {
		return raw
	}
	if len(arr) == 0 {
		return "—"
	}
	return strings.Join(arr, ", ")
}

// ExportMarkdown generates a professional forensic PoC report in Markdown.
// CRITICAL for demo video: MUST include HTTP body snippets as code blocks.
func ExportMarkdown(scan *storage.Scan) ([]byte, error) {
	var b strings.Builder

	// Header
	b.WriteString("# Subdomain Takeover Vulnerability Report\n\n")
	b.WriteString(fmt.Sprintf("**Target Domain:** `%s`\n", scan.Domain))
	b.WriteString(fmt.Sprintf("**Scan ID:** %d\n", scan.ID))
	b.WriteString(fmt.Sprintf("**Scan Date:** %s\n", scan.StartedAt.Format(time.RFC1123)))
	b.WriteString(fmt.Sprintf("**Total Subdomains:** %d\n", scan.SubdomainCount))
	b.WriteString(fmt.Sprintf("**Vulnerabilities Found:** %d\n\n", scan.VulnCount))

	b.WriteString("---\n\n")

	// Summary table
	b.WriteString("## Executive Summary\n\n")
	b.WriteString("| Subdomain | Service | Risk Score | Status |\n")
	b.WriteString("|-----------|---------|------------|--------|\n")
	for _, f := range scan.Findings {
		service := f.FingerprintService
		if service == "" {
			service = "N/A"
		}
		status := "Safe"
		if f.IsVulnerable {
			status = "**VULNERABLE**"
		}
		b.WriteString(fmt.Sprintf("| `%s` | %s | %d | %s |\n",
			f.Subdomain, service, f.TakeoverRisk, status))
	}
	b.WriteString("\n---\n\n")

	// Detailed findings for vulnerable subdomains only.
	vulnCount := 0
	for _, f := range scan.Findings {
		if !f.IsVulnerable {
			continue
		}
		vulnCount++
		b.WriteString(fmt.Sprintf("## Finding #%d: `%s`\n\n", vulnCount, f.Subdomain))

		// Service identification
		b.WriteString(fmt.Sprintf("**Service:** %s\n\n", f.FingerprintService))
		b.WriteString(fmt.Sprintf("**Risk Level:** %d/100\n\n", f.TakeoverRisk))

		// DNS evidence
		b.WriteString("### DNS Evidence\n\n")
		b.WriteString(fmt.Sprintf("- **CNAME Chain:** `%s`\n", cleanJSONArr(f.CNAMEChain)))
		b.WriteString(fmt.Sprintf("- **A Records:** `%s`\n", cleanJSONArr(f.ARecords)))
		if f.NXDomain {
			b.WriteString("- **NXDomain:** true (CNAME target does not exist)\n")
		}
		if f.Wildcard {
			b.WriteString("- **Wildcard DNS:** detected\n")
		}
		b.WriteString("\n")

		// HTTP verification evidence - CRITICAL for forensic report
		b.WriteString("### HTTP Verification\n\n")
		if f.HTTPStatus > 0 {
			b.WriteString(fmt.Sprintf("**HTTP Status Code:** %d\n\n", f.HTTPStatus))
		}
		if f.HTTPBodySnippet != "" {
			b.WriteString("**HTTP Response Body (snippet):**\n\n")
			b.WriteString("```\n")
			b.WriteString(f.HTTPBodySnippet)
			if !strings.HasSuffix(f.HTTPBodySnippet, "\n") {
				b.WriteString("\n")
			}
			b.WriteString("```\n\n")
		}
		if f.ErrorMsg != "" {
			b.WriteString(fmt.Sprintf("**Connection Error:** `%s`\n\n", f.ErrorMsg))
		}

		// Remediation
		b.WriteString("### Remediation\n\n")
		b.WriteString(fmt.Sprintf("The subdomain `%s` has a CNAME record pointing to `%s` ",
			f.Subdomain, cleanJSONArr(f.CNAMEChain)))
		b.WriteString(fmt.Sprintf("which appears to be an unclaimed %s resource. ", f.FingerprintService))
		b.WriteString("An attacker could claim this resource and serve malicious content under this subdomain.\n\n")
		b.WriteString("**Action Required:** Delete the dangling DNS record or claim the cloud resource to prevent takeover.\n\n")

		b.WriteString("---\n\n")
	}

	if vulnCount == 0 {
		b.WriteString("## No Vulnerabilities Detected\n\n")
		b.WriteString("All subdomains appear to be properly configured. No dangling CNAME records were found.\n\n")
	}

	// Footer
	b.WriteString(fmt.Sprintf("\n*Report generated by subtakeover on %s*\n", time.Now().Format(time.RFC1123)))

	return []byte(b.String()), nil
}
